[ -n "$PS1" ] && source ~/.bash_profile

# Fix Spotify scaling issues
alias spotify="/usr/bin/spotify --force-device-scale-factor=1.5"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# added by travis gem
[ -f /home/smona/.travis/travis.sh ] && source /home/smona/.travis/travis.sh

